### ISSUE TITLE
Running `run_simulation.py` significantly changes checked in OUTPUT values

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/dynamic#107]
I'm interested in making significant structural changes to the `dynamic` package (soon to be renamed `ogusa`?) but I need to know that my changes aren't affecting the answer. So, I checked out a clean version of the repo, and then ran `run_simulation.py`, which was my refactored version of the original script that ran everything. Running this script changes a lot of files currently checked in to the repo. That list of files is as follows:

```
	modified:   Python/OUTPUT/SSinit/ss_init_tpi_vars.pkl
	modified:   Python/OUTPUT/SSinit/ss_init_vars.pkl
	modified:   Python/OUTPUT/Saved_moments/SS_init_solutions.pkl
	modified:   Python/OUTPUT/Saved_moments/labor_data_moments.pkl
	modified:   Python/OUTPUT/Saved_moments/wealth_data_moments.pkl
	modified:   Python/OUTPUT/TPI_K.png
	modified:   Python/OUTPUT/TPIinit/TPIinit_vars.pkl
```
For each of the pickle files, I ran a comparison check using the utility function `pickle_file_compare` in my [recent PR](https://github.com/OpenSourcePolicyCenter/dynamic/pull/102). I checked out another clean version of the repo in a different directory (since the code overwrites what is currently in master). For each pickle file (the clean one in master and the results of running `run_simulation.py`), I captured the output of the `pickle_file_compare`. The output of this utility function is kind of rough, but I cleaned up and condensed some of it. The gist is here:

https://gist.github.com/talumbau/7fef7b31c88a20b9fce1

There are two overall results:

- Many of the values that are different are different by numerical 'noise'. It significantly higher than something like round off error, but I could set either an absolute or relative tolerance for those values and it would be fine. Some examples from the gist:

For the file Python/OUTPUT/SSinit/ss_init_tpi_vars.pkl:
```
'nssmat_init: 
[[ 0.32211472  0.37224071  0.3898083   0.39204884  0.39629503  0.38399747\n   0.28474527]]

[[ 0.32211454  0.37224101  0.38980968  0.39205109  0.39629851  0.38400308\n   0.28475163]]',
```
The first array is one element of `nssmat_init` from running `run_simulation.py`, the second is from master. Not exactly the same, but I could set a tolerance and pass a comparison.

- The values in TPIinit_vars.pkl are wildly different. For example:

```
'rinit: [-0.03865203] [ 0.07479938]
'Yinit: [ 0.45646764] [ 0.53933587]'
```

I think I'm probably just doing something wrong/incomplete, because @evan-magnusson merged https://github.com/OpenSourcePolicyCenter/dynamic/pull/94 which seemed to have a very thorough treatment of this issue (making sure the new Python code got the same answers as the old). However, I'm not sure how to proceed until I figure out how to write a test to make sure I get the same answer as well.

cc @rickecon @evan-magnusson @MattHJensen

**Comment by evan-magnusson** [comment]
The negative value for rinit is strange -- it must be strictly positive.  Also, did both run for the entire 40 minutes or so that it probably took?

**Comment by talumbau** [comment]
For `rinit` above, the left hand one is from running `run_simulation.py` all the way to the end. Yes, it took about that amount of time. The value of `rinit` on the right is what is currently in the `/Python/OUTPUT/TPIinit/TPIinit_vars.pkl` file in master right now. 

@evan-magnusson would you mind repeating the experiment above and seeing if you get the same result? For our purposes, a very focused experiment would be:

1. checkout the latest master in a repo, say `dynamic1`.
2. Run `python run_simulation.py` to the end.
3. checkout the latest master in another repoo, say `dynamic2`.
4. compare the value of `rinit` inside of `/Python/OUTPUT/TPIinit/TPIinit_vars.pkl` in repo `dynamic1` with the value of `rinit` inside of `/Python/OUTPUT/TPIinit/TPIinit_vars.pkl` in repo `dynamic2`.

I suspect you will get answers similar to what I have shown above.

**Comment by evan-magnusson** [comment]
What was in the current pickle file is probably incorrect -- I don't think I ran it all the way through the last time I ran it.  I'm running it all the way through with what is on my laptop now and seeing what happens with rinit.

**Comment by evan-magnusson** [comment]
I'm actually getting the same answer that is in the master file -- .074

**Comment by talumbau** [comment]
wow. well, this is good because now we know what must be solved in order to proceed. Can you post the following:

- for the repo where the only thing you did was type `cd Python; python run_simulation.py`, can you show  the output of `git status`

- the output of `conda list`

- the output of `conda info`

That might give me a hint as to what to check on my machine.

**Comment by evan-magnusson** [comment]
On branch master
Your branch is up-to-date with 'origin/master'.

'Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   OUTPUT/TPI_K.png
        modified:   OUTPUT/TPIinit/TPIinit_vars.pkl

no changes added to commit (use "git add" and/or "git commit -a")'

'# packages in environment at C:\Users\Evan\Anaconda:
#
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
_license                  1.1                      py27_0
anaconda                  2.2.0                np19py27_0
argcomplete               0.8.4                    py27_0
astropy                   1.0.1                np19py27_0
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.8.1                np19py27_0
beautiful-soup            4.3.2                    py27_1
beautifulsoup4            4.3.2                     <pip>
binstar                   0.10.1                   py27_3
bitarray                  0.8.1                    py27_1
blaze                     0.7.3                     <pip>
blaze-core                0.7.3                np19py27_0
blz                       0.6.2                np19py27_0
bokeh                     0.8.1                np19py27_1
boto                      2.36.0                   py27_0
cdecimal                  2.3                      py27_1
certifi                   14.05.14                 py27_0
cffi                      0.9.2                    py27_0
clyent                    0.3.4                    py27_0
colorama                  0.3.3                    py27_0
conda                     3.14.0                   py27_0
conda-build               1.11.0                   py27_0
conda-env                 2.1.4                    py27_0
conda311fix               1.0                           0
configobj                 5.0.6                    py27_0
cryptography              0.8                      py27_1
cython                    0.22                     py27_0
cytoolz                   0.7.2                    py27_0
datashape                 0.4.4                np19py27_1
decorator                 3.4.0                    py27_0
docutils                  0.12                     py27_1
dynd-python               0.6.5                np19py27_0
enum34                    1.0.4                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
funcsigs                  0.4                      py27_0
futures                   2.2.0                    py27_0
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
greenlet                  0.4.5                    py27_0
grin                      1.2.1                    py27_2
h5py                      2.4.0                np19py27_0
httplib2                  0.9.1                     <pip>
ipython                   3.0.0                    py27_1
ipython-notebook          3.0.0                    py27_2
ipython-qtconsole         3.0.0                    py27_1
itsdangerous              0.24                     py27_0
jdcal                     1.0                      py27_0
jedi                      0.8.1                    py27_0
jinja2                    2.7.3                    py27_2
jsonschema                2.4.0                    py27_0
launcher                  1.0.0                         1
llvmlite                  0.2.2                    py27_1
lxml                      3.4.2                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.4.3                np19py27_1
menuinst                  1.0.4                    py27_0
mistune                   0.5.1                    py27_0
mock                      1.0.1                    py27_0
multipledispatch          0.4.7                    py27_0
networkx                  1.9.1                    py27_0
nltk                      3.0.2                np19py27_0
node-webkit               0.10.1                        0
nose                      1.3.4                    py27_1
numba                     0.17.0               np19py27_0
numexpr                   2.3.1                np19py27_0
numpy                     1.9.2                    py27_0
odo                       0.3.1                np19py27_0
openpyxl                  1.8.5                    py27_0
pandas                    0.15.2               np19py27_1
patsy                     0.3.0                np19py27_0
pep8                      1.6.2                    py27_0
pillow                    2.7.0                    py27_0
pip                       6.1.1                    py27_0
ply                       3.4                      py27_0
psutil                    2.2.1                    py27_0
py                        1.4.26                   py27_0
pyasn1                    0.1.7                    py27_0
pybing                    0.12                      <pip>
pycosat                   0.6.1                    py27_0
pycparser                 2.10                     py27_0
pycrypto                  2.6.1                    py27_3
pyflakes                  0.8.1                    py27_0
pygments                  2.0.2                    py27_0
pyopenssl                 0.14                     py27_0
pyparsing                 2.0.3                    py27_0
pyqt                      4.10.4                   py27_1
pyreadline                2.0                      py27_0
pytables                  3.1.1                np19py27_1
pytest                    2.6.4                    py27_0
python                    2.7.9                         1
python-dateutil           2.4.1                    py27_0
pytz                      2015.2                   py27_0
pywin32                   219                      py27_0
pyyaml                    3.11                     py27_0
pyzmq                     14.5.0                   py27_0
requests                  2.7.0                    py27_0
rope                      0.9.4                    py27_1
runipy                    0.1.3                    py27_0
scikit-image              0.11.2               np19py27_0
scikit-learn              0.15.2               np19py27_0
scipy                     0.15.1               np19py27_0
setuptools                15.2                     py27_0
six                       1.9.0                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.2.3                    py27_0
spyder                    2.3.4                    py27_1
spyder-app                2.3.4                    py27_0
sqlalchemy                0.9.9                    py27_0
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1                np19py27_0
sympy                     0.7.6                    py27_0
tables                    3.1.1                     <pip>
toolz                     0.7.1                    py27_0
tornado                   4.1                      py27_0
ujson                     1.33                     py27_0
unicodecsv                0.9.4                    py27_0
werkzeug                  0.10.1                   py27_0
xlrd                      0.9.3                    py27_0
xlsxwriter                0.6.7                    py27_0
xlwings                   0.3.4                    py27_0
xlwt                      0.7.5                    py27_0'

'Current conda install:

             platform : win-64
        conda version : 3.14.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Users\Evan\Anaconda  (writable)
  default environment : C:\Users\Evan\Anaconda
     envs directories : C:\Users\Evan\Anaconda\envs
        package cache : C:\Users\Evan\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False'

**Comment by evan-magnusson** [comment]
Sorry for the formatting

**Comment by talumbau** [comment]
How is it that you could run `python run_simulation.py` and only have those two files changed? When I run it the list of changed files is bigger.

Your list:

```
    modified:   OUTPUT/TPI_K.png
    modified:   OUTPUT/TPIinit/TPIinit_vars.pkl
```

My list (reported above):
```
    modified:   Python/OUTPUT/SSinit/ss_init_tpi_vars.pkl
    modified:   Python/OUTPUT/SSinit/ss_init_vars.pkl
    modified:   Python/OUTPUT/Saved_moments/SS_init_solutions.pkl
    modified:   Python/OUTPUT/Saved_moments/labor_data_moments.pkl
    modified:   Python/OUTPUT/Saved_moments/wealth_data_moments.pkl
    modified:   Python/OUTPUT/TPI_K.png
    modified:   Python/OUTPUT/TPIinit/TPIinit_vars.pkl
```

**Comment by evan-magnusson** [comment]
I must have pushed all of those files in my last commit.  If something in your parameters or SS simulation changed from my last PR, then that would explain it.

**Comment by talumbau** [comment]
Hmm.. can you also execute as follows:

```
git log -n 1
```
and show me the output? You should output something like this:

```
(heroku_aei)0054-tjalumbaugh:dynamic talumbau$ git log -n 1
commit 3260071f94e2c36d1871ae7c7adc1871e9881050
Merge: 43fac98 f281bd8
Author: T.J. Alumbaugh <talumbau@users.noreply.github.com>
Date:   Sun Aug 9 16:06:41 2015 -0500

    Merge pull request #103 from talumbau/license

    MIT license file
```
This should be both for the repo that is unchanged and the repo where you executed `python run_simulation.py`.

**Comment by evan-magnusson** [comment]
C:\Users\Evan\Documents\GIT_repos\dynamic\Python>git log -n 1
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x270000, State 0x10000
C:\Program Files (x86)\Git\bin\less.exe: *** Couldn't reserve space for cygwin's
 heap, Win32 error 0

**Comment by evan-magnusson** [comment]
@talumbau Maybe I'm doing the wrong thing -- what do you mean the unchanged repo and the repo where I executed the command?
     The code I ran today was the code I pushed a 2-4 weeks ago on my last PR.  I haven't pulled since then.

**Comment by talumbau** [comment]
Ah, OK. I will explain more about 'unchanged repo' and 'repo where I executed the command'. First though, it is good to know that you are running on the code as it was in your last commit. I will sync to that change, re-run, and report results.

**Comment by talumbau** [comment]
I ran the code again with the repo synced to the last change you made and got the same answer I've reported above (`rinit = -0.03865203`) so I think I need to know more about the directory where you are running the code. It's a bummer that you are getting a crash when attempting to run `git log -n 1`. It seems are you running that in Cygwin. git on Windows does have it's own command line program. I think it's called Git Bash. Could you go to the directory with that program and run `git log -n 1` again and see if you actually get output.

@evan-magnusson are you free to do a Google Hangout tomorrow at some point? I think with 15 minutes of interactive poking around, we should be able to figure out what is going on.

**Comment by talumbau** [comment]
Just to give a complete answer to your question above, I am doing the comparison of pickle files with the two repos:

Repo 1: The Unchanged Repo
This is a repo I get by typing `git clone git@github.com:OpenSourcePolicyCenter/dynamic` and then doing nothing.

Repo 2: The Repo where I'm running the simulation
This is a second repo I get by typing  `git clone git@github.com:OpenSourcePolicyCenter/dynamic` in a different directory and then, once the repo is cloned, I do as follows:
```
cd dynamic/Python
python run_simulation.py
```
Then I compare all of the changed pickle files in Repo 2 with their unchanged versions in Repo 1. The goal is to find that nothing substantially changes when running `run_simulation.py`.

**Comment by evan-magnusson** [comment]
![gitlog](https://cloud.githubusercontent.com/assets/10715898/9262863/18226218-41cd-11e5-8e7b-25e9b443050f.PNG)

**Comment by evan-magnusson** [comment]
@talumbau I should be around tomorrow.  I'm also around for the rest of today -- let me know what works for you.

**Comment by talumbau** [comment]
So odd. Here is my repo:
<img width="625" alt="screen shot 2015-08-13 at 5 08 55 pm" src="https://cloud.githubusercontent.com/assets/1891418/9262888/2082f07e-41de-11e5-9ae9-604a7b8b9c18.png">

I synced to 8b3ca11 and then ran all the way through.

**Comment by talumbau** [comment]
Update on this issue: I got a Windows 7 VM and ran `run_simulation.py` with the conda environment created from the `environment.yml`. I had the same set of modified files as I previously reported, BUT the `rinit` value now aligns with what Evan gets. I will do a more detailed analysis soon. I believe we are seeing a difference in output due to the platform we are running on, which is quite unusual. More results to come. cc @evan-magnusson @MattHJensen @rickecon

**Comment by rickecon** [comment]
Uh oh. Platform influencing results is not a good thing.

**Comment by evan-magnusson** [comment]
I noticed this back in december, when getting different output on my laptop (Windows 8) and the windows machine at BYU (windows 7) and Rick's machine.  The biggest thing this affected at the time was the calibration -- but we're not even doing that here.  When I was going through it, I found that making the tolerance values in fsolve as small as possible (1x10^-14) decreased this problem a lot (but did not get rid of it).

**Comment by talumbau** [comment]
Something else may be going on. @evan-magnusson, can you do as follows on your system. Please pick a completely clean repo (with no modified files) and open the `TPIinit_vars.pkl` file as follows:

```
>>> import cPickle as pickle
>>> f = open("TPIinit_vars.pkl")
>>> xx = pickle.load(f)
```

Here is what I get when I look at the `rinit` variable:

```
>>> xx['rinit']
array([-0.03865203, -0.04317084, -0.03877133, -0.03866454, -0.03853498,
       -0.03837308, -0.03816687, -0.03790512, -0.03758002, -0.0371745 ,
       -0.03666771, -0.03661074, -0.03655827, -0.03650896, -0.03646434,
       -0.04211799, -0.04099433,         nan,         nan,         nan,
       -0.03822229, -0.03822229, -0.03822229, -0.03822229, -0.03822229,
       -0.03822229, -0.03822229, -0.03822229, -0.03822229, -0.03822229])
>>> exit()
```
This is incorrect, right? It should start with something like `0.07479938`, yes? I suspect that on your system, you will open the file and get the correct array. If this is true, then I think I know what the issue is. Please try the above code when you can. Thanks!

**Comment by evan-magnusson** [comment]
Yep, I got the correct array.  It started at .0747995

**Comment by talumbau** [comment]
Awesome. I believe I know what has happened. It turns out that writing binary data to files on Windows has an annoying feature: the newline character. In order for this to be interpreted correctly on other systems, you have to write the file in 'binary' mode. This means that when opening a file for writing on Windows, you have to specify a mode of `wb` instead of just `w`. This is true for any file that will contain binary data written on Windows through Python. In particular, the pickle files that we are using to hold the current answer, because they include numpy arrays, we must specify a binary write mode. There is no harm for specifying the extra 'b' for Mac and Linux since they do the same thing in both cases. So, I would propose as follows:

Evan, please modify [this](https://github.com/OpenSourcePolicyCenter/dynamic/blob/master/Python/dynamic/TPI.py#L448) line of code to say as follows:

```
    pickle.dump(output, open("OUTPUT/TPIinit/TPIinit_vars.pkl", "wb"))
```
and similarly for every pickle dump in the code. Also, for every pickle load in the code, please specify a read mode of `rb`. Then run the simulation (`run_simulation.py`) from master. The pickle files will all be modified (which is good) but if you dig inside of them, you should see that the actual values remain the same. Then post this as a PR. I will sync with your branch and verify that I can load these files and get correct arrays on Windows 7, Mac, and Linux. Sound like a plan?

**Comment by evan-magnusson** [comment]
Sounds good.

**Comment by evan-magnusson** [comment]
@talumbau It is PR #108 .  I ran it, looks good.

**Comment by talumbau** [comment]
closed via https://github.com/OpenSourcePolicyCenter/dynamic/pull/108
