### ISSUE TITLE
What is the proper error metric for the results of running the model?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/dynamic#115]
Now that we have resolved the issue with the pickle files, I updated the comparison functions with this PR:

https://github.com/OpenSourcePolicyCenter/dynamic/pull/114

and I used that function in order to see the level of error when just running the basic simulation. The test file looked like this:

https://gist.github.com/talumbau/47e9bd02ad9698bcfe04

I output the results to a file, which you can see here:

https://gist.github.com/talumbau/657f208367edd024848e

Most of the values have an error within an acceptable range. There are some concerning error levels though. In particular, these error rates are troubling:

in ss_init_vars.pkl:

```
diff for bssmat_s is 0.00147395404773 which is NOT OK
diff for factor_ss is 0.754183860641 which is NOT OK
diff for bssmat_splus1 is 0.00162147841888 which is NOT OK
```

in SS_init_solutions.pkl:

```
diff for solutions is 0.754183860641 which is NOT OK
```

in TPI_init_vars.pkle:

```
diff for b_mat is 0.00362436350586 which is NOT OK
diff for c_path is 0.0047934971713 which is NOT OK
```

I will run these on a Windows VM just to make sure there are no platform issues, but I don't have a good sense of if these error levels are OK. To be clear, this is a comparison of all of the pickle files in master versus the state of the pickle files after running run_simulation.py. This is an absolute measure of the difference, so maybe in some cases a relative error metric would be better. Any thoughts on this would be appreciated. cc @evan-magnusson @rickecon @jdebacker @MattHJensen

**Comment by talumbau** [comment]
for some reference:

`bbsmat_s` is a numpy array of shape (80, 7) with a max of 87.520727775315791, mean of 8.0493978367920835 and min of 0.0

`bbsmat_s` is a numpy array of shape (80, 7) with a max of 87.520727775315791, mean of 8.0493978367920835 and min of 0.0

`factor_ss` is a scalar equal to 179436.48618511992

`bssmat_splus1` is an array of shape (80,7), max of 89.452041776928212, min of 0.022723523254224953 and mean 8.2734565816308017

`solutions` is an array of shape (1124,), max of 179436.48618511992, min of 0.011653966176984784 and mean of 163.89156041412156

`b_mat` is an array of shape (240, 80. 7), max of 95.246160048505004, min of 0.0, mean of 7.398549236956633

`c_path` is as follows:

```
>>> np.max(c_path)
2.898146087925614
>>> np.min(c_path)
0.11529022511398385
>>> np.mean(c_path)
0.62697486728371243
>>> np.shape(c_path)
(160, 80, 7)
```

So, to me it seems like at least the `solutions` variable should have a relative error metric and not absolute because the values vary over about 7 orders of magnitude.

**Comment by jdebacker** [comment]
@talumbau I am following this issue, but I don't know enough to contribute.  However, if this is not resolved by Wednesday, perhaps we can have a call that day with @rickecon to get me up to speed.

**Comment by talumbau** [comment]
I ran on Windows 7 and only four of the values had L_inf norms above the tolerance I set. They output is below:

```
diff for factor_ss is 0.0443678515148 which is NOT OK

diff for solutions is 0.0443678515148 which is NOT OK

diff for b_mat is 0.00192638398251 which is NOT OK

diff for c_path is 0.00251473000289 which is NOT OK
```

So, on Windows, the differences for `bssmat_s` and `bssmat_splus1` were smaller than on Mac.

**Comment by talumbau** [comment]
@jdebacker yes, I think it would be great to set up a call. I really only want to come up with the right test so that I can do more extensive refactoring on the package. I might be 'barking up the wrong tree', but it might also be an issue of a solution that is quite sensitive to initial conditions.

**Comment by rickecon** [comment]
@talumbau and @jdebacker , we have been building up some code in separate repos underneath this to try and figure out where those errors are coming from. Let's chat to discuss strategy.

**Comment by talumbau** [comment]
I can meet on Thursday. Does that work for the both of you?

**Comment by rickecon** [comment]
Anytime on Thursday works for me.

**Comment by rickecon** [comment]
@talumbau . During July after your visit to Provo, we found an error in the baseline dynamic model code that was pretty big (10 percent errors in two equations). Evan and I worked on finding it for about three weeks. We found two big coding errors that were causing two equations to not be satisfied. However, these equations were not necessary in the computation due to a theoretical consideration. However, their not being satisfied was evidence of something wrong in the code.

The two errors that we fixed reduced the error in the two equations from about 10 percent down to less than 1 percent. However, as evidenced in issue #115, that error of 1 percent is still not acceptable and is evidence of a coding error somewhere. We think we have narrowed down the location of the error to be in the function that computes population weights for the stationarized model. We think this because the error goes away when we include a mortality rate in two of the characterizing equations (Total Bequests BQ and the savings Euler equations) in a place where those mortality rates should not be.

We are working on trying to fix that function that computes the population weights by recreating it from scratch. @jdebacker @evan-magnusson

**Comment by evan-magnusson** [comment]
@rickecon That coding error shouldn't affect anything currently, because the immigration rates are set to zero until the problem is fixed, so the error is on the scale of 1x10^-11

**Comment by jdebacker** [comment]
@talumbau @rickecon How's Thursday at 11:15am central time?  I'm available from 11:15-2pm CT.

**Comment by talumbau** [comment]
I can do Thursday at 11:15am central time as well. I would need to be done by 12:45 central time.

**Comment by talumbau** [comment]
Some news to report:

1. I got the results from @evan-magnusson of printing out the starting values of every value in all pickle files. All platforms report the same starting values, so no more worries there
2. I re-ran `run_simluation.py` through SS and TPI and got the exact same answers reported in the issue on Mac OS X and Windows 7. So, even if the differences are due to some numerical drift with repeated `fsolve`s or finding slightly different zeros on flat functions, the behavior is exactly reproducible on each platform.
3. Using the updates to the comparison functions (in #116) I measured relative errors for the differences reported above. The results are generally good. The comparison is method is as follows:
  1. if the two values are below some epsilon (or arrays where every value < epsilon) we say that they are equal
  2. relative error for arrays of values is defined as: `np.max( abs(a-b)/ np.mean(b) )`. This helps deal with arrays that have zeros in them.
4. Using that method, I found two values that were above the (arbitrary) relative error threshold I set at 1e-3. The two values were:
   
```
diff for tax_path is 0.0625308203757 which is NOT OK
diff for c_path is 0.00764543987157 which is NOT OK
```

So the max relative error in the `tax_path` array is about 6 percent and the max relative error in the `c_path` array is about 0.7 percent. So, the values that were previously concerning to @rickecon `bss_mat_s` and `bss_mat_splus1` are OK by this metric.

Should there be concern over the relative differences in `tax_path` and `c_path`? cc @jdebacker @isaacswift @evan-magnusson @rickecon @MattHJensen

**Comment by rickecon** [comment]
OK @talumbau is right that those differences in tax_path and c_path are not OK. But I am glad that our conjecture that the difference in the other objects were small in relative terms looks like it was true. Are those errors in tax_path and c_path generated using consecutive runs on the same platform, or are they generated on different platforms?

**Comment by talumbau** [comment]
The errors above in `tax_path` and `c_path` are the differences between running `run_simulation.py` on Mac OS X and what the values are as checked in to master, which I believe were generated by @evan-magnusson who told me he runs on Windows 10. It appears that you always get the same answers on each platform (at least I did with two runs on Mac OS X and two runs on Windows 7) but that these values are slightly different from the checked in values which were run on Windows 10.

**Comment by evan-magnusson** [comment]
I wonder also if either of us are running different versions of python, ie any of our packages are out of sync?  Or did we rule that out when we did the skype call?

**Comment by rickecon** [comment]
I wonder if it is an integer vs. float issue stemming from Python 2.7. I say that because it is hard to imagine fsolves creating differences in variables in relative terms of 0.7 percent. Another possible explanation is that the levels of tax_path and c_path are so small at the offending points that the percent differences are amplified. A cure for this would be an epsilon rule for which a difference is "not OK" if both the relative difference and the difference in levels are above some criterion.

**Comment by talumbau** [comment]
@evan-magnusson I took at a look at your version of scipy when you did a `conda list` in this issue: https://github.com/OpenSourcePolicyCenter/dynamic/issues/107
It looked OK to me. @evan-magnusson one good check would be to run this code:

https://gist.github.com/talumbau/6772f6aa87e5596b389a

Save it as comp.py in the Python folder and change the file names to be one set of unchanged pickle files and one set of pickle files to be after running `run_simulation.py`.

**Comment by talumbau** [comment]
Oh, I will need to merge #116 first so you have the option of running with relative error.

**Comment by talumbau** [comment]
It would be great if you also got the relative errors I reported above, because then we would know that the reference data is old.

**Comment by talumbau** [comment]
To truly address package version issues, you could do as follows on Windows when running your test:

```
<cd to top of repo>
conda env create
activate oscpdyn
cd Python
python run_simulation.py
```

This will make the `ospcdyn` environment on Windows with the latest version of the required packages.

**Comment by talumbau** [comment]
Then run the `comp.py` as specified above to get the output showing the differences between your run and the unchanged pickle files in master.

**Comment by evan-magnusson** [comment]
It's running -- should have some results in the next hour.  Do you want those emailed to you?

**Comment by evan-magnusson** [comment]
My python just crashed right before all the results were saved.  I'll have to rerun it tonight.

**Comment by talumbau** [comment]
you can just update this issue with the results. Copy/paste is fine. Also, I have seen this issue on Windows 7 where it pops up a window saying the program has stopped right before finishing. One of the options on the window I have seen leaves the Python prompt up and one kills everything. I can't remember the specifics. Anyway, I have seen that and was still able to get results after the crash. thanks for re-running though!

**Comment by evan-magnusson** [comment]
It just happened again.  I've seen this before, but it has been pretty rare, and usually just when I'm using a text editor to run the code, not when I'm doing it from the command prompt.  3rd time's the charm, hopefully.

**Comment by talumbau** [comment]
Next time can you do a screen capture and post? wondering if it's exactly the same thing I'm seeing when I run sometimes.

**Comment by evan-magnusson** [comment]
It finished last night.  I'll run comp.py, but I noticed something: ss_output.pkl is only made by run_small, not run_simulation.  I deleted it to make sure that everything was finishing, and I noticed this morning that it wasn't made.  Do we want to make ss_output.pkl after we run run_simulation.py?

**Comment by evan-magnusson** [comment]
trying a pair
OUTPUT_old/SSinit/ss_init_tpi_vars.pkl OUTPUT/SSinit/ss_init_tpi_vars.pkl
err is 0.0 which is OK
err is 0.0 which is OK
next pair
trying a pair
OUTPUT_old/SSinit/ss_init_vars.pkl OUTPUT/SSinit/ss_init_vars.pkl
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
next pair
trying a pair
OUTPUT_old/Saved_moments/SS_init_solutions.pkl OUTPUT/Saved_moments/SS_init_solutions.pkl
err is 0.0 which is OK
err is 0.0 which is OK
next pair
trying a pair
OUTPUT_old/Saved_moments/labor_data_moments.pkl OUTPUT/Saved_moments/labor_data_moments.pkl
err is 0.0 which is OK
next pair
trying a pair
OUTPUT_old/Saved_moments/wealth_data_moments.pkl OUTPUT/Saved_moments/wealth_data_moments.pkl
err is 0.0 which is OK
next pair
trying a pair
OUTPUT_old/TPIinit/TPIinit_vars.pkl OUTPUT/TPIinit/TPIinit_vars.pkl
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
err is 0.0 which is OK
next pair

**Comment by talumbau** [comment]
OK, This is good info. Now we know for sure that we do have the correct reference data in master. from this issue: https://github.com/OpenSourcePolicyCenter/dynamic/issues/107, we have your conda environment and you said your platform is Windows 10, correct?

**Comment by evan-magnusson** [comment]
Indeed.

**Comment by talumbau** [comment]
Update: I ran everything on Windows 10. I got some interesting results. First, I had errors when running the comparison code above. This was really amazing to me. It appears that on Windows 10, I have to open the files in 'text' mode (e.g. `open(fname1, 'r')` in order to read them. I have no explanation for this. I wonder if there is a bug in cPickle for Python 2.7 on Windows 10. After I changed the `pickle_file_compare` function in `utils.py` to account for this, I was able to read the files in and got only two values that did not meet my criteria: tax_path and c_path again

```
diff for tax_path is 0.0182344808045 which is NOT OK
err is 0.000260373015252 which is OK
err is 1.47090998652e-07 which is OK
err is 1.49406913644e-06 which is OK
err is 5.962414104e-07 which is OK
err is 5.0738403772e-05 which is OK
err is 1.92415795861e-06 which is OK
diff for c_path is 0.00401089427882 which is NOT OK
```

The error was smaller than when running on Mac OS X. I believe I have what I need to create a temporary error metric for some code changes. I will simply create a test that only allows relative errors above 1e-4 for two values (tax_path and c_path) and there will be a max error value that depends on the platform. This is probably overkill for my changes, which at first won't be substantive at all, but mostly stylistic. The purpose is to make sure that I don't accidentally delete a line of code or change arguments to a function. This kind of test should be suitable for changes of that sort.

We can then have as a separate activity the task of figuring out why there are different outputs on different platforms (and even different machines with the same platform!). A further question is "why was Evan able to successfully run the file comparisons on Windows 10 while I had to modify the pickle reading code to open in non-binary mode on Windows 10?"

-T.J.

**Comment by talumbau** [comment]
this is a relevant StackOverflow post of someone having a similar issue:

http://stackoverflow.com/questions/3004792/cpickle-importerror-no-module-named-multiarray

**Comment by rickecon** [comment]
From the stackoverflow thread, it looks like the only solution that we have not tried is moving our import statements. We have changed the pickle call to the 'wb' option and we have checked Python versions.

**Comment by evan-magnusson** [comment]
@talumbau Could running things in the ospcdyn environment (or not) make a difference as to why I didn't have to change the files?

**Comment by talumbau** [comment]
@evan-magnusson I don't think so. I don't know enough about the pickle format to get as deep in the weeds as we are getting.

**Comment by talumbau** [comment]
With the merge of https://github.com/OpenSourcePolicyCenter/dynamic/pull/113, I have asserted a relative error metric along with the possibility of adding platform-specific tolerance settings for individual variables. This seems good enough for now and can be revisited in the future.
