### ISSUE TITLE
The call to `SS_solver` in `function_to_minimize` uses a globally scoped variable

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/dynamic#119]
I'm uncertain if this is a bug, but flagging as one for now. I went back and looked at how this function was defined prior to the refactoring and it's the same as what I describe now. This line:

https://github.com/OpenSourcePolicyCenter/dynamic/blob/master/Python/dynamic/SS.py#L252

makes a call to `SS_solver` and one of the arguments is the variable `rho`. However, the argument passed in to this function is `rho_vec`, and there is no `rho` defined at local scope. The only reason the call succeeds is because `rho` is defined elsewhere at global scope. This seems bad. So the questions are:

1. Is it intention to call `SS_solver` with `rho` instead of `rho_vec`?

2. If so, should we pass `rho` explicitly in to `function_to_minimize` so that we don't reach in to the global scope to get the `rho` variable for the call to `SS_solver`?

My answer for the seoncd question is 'yes'. I don't know the answer to the first question. Would appreciate enlightenment @rickecon @evan-magnusson @isaacswift @jdebacker

**Comment by evan-magnusson** [comment]
As I recall, I think rho and rho_vec are exactly the same array....   I probably forgot to change that instance from rho to rho_vec.

**Comment by talumbau** [comment]
yes, when I ran the debugger, I found that in the places where the code stopped `rho` and `rho_vec` were the same. I will make the change in a separate PR so that the git commit history shows this change (in case we need to go back at some point and pinpoint an issue with the change).
