### ISSUE TITLE
make a .py file which calibrates the wealth tax to the baseline

### ISSUE THREAD

**Issue by evan-magnusson** [OpenSourcePolicyCenter/dynamic#34]
Currently, we use the excel spreadsheet to calibrate the wealth tax to the baseline distribution of wealth.  Move this to a python file that can be called within run_tax_experiments.py to skip this step.

**Comment by evan-magnusson** [comment]
This may no longer be important, as this is more related to the wealth tax paper.  The only reason this would matter would be to make it easier for uses of the code to calibrate a wealth tax, which may be beyond the scope of what we're doing right now.

**Comment by jdebacker** [comment]
Yes - I think we'll find a different calibration for the dynamic scoring model.  Having to solve the model to calibrate it too computationally intensive.

**Comment by evan-magnusson** [comment]
Ok, we'll close this issue for now, and once we get to the point of needing to implement a wealth tax, we'll decide a new way of doing so.
