### ISSUE TITLE
make the code base into a Python package

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/dynamic#66]
It's best to work with Python code as a package. It's easier to call certain pieces of the code and share it with others. I'll have a go at making a package. I intend to start with the code in `Python/TESTED_DONT_TOUCH`, since the goal is to create a Python package of the current "gold standard" version of the model. Let me know if I should start somewhere else @evan-magnusson @rickecon @isaacswift @jdebacker

**Comment by evan-magnusson** [comment]
@talumbau I'm making a couple changes to that folder today, actually only in the TPI.py file.  I'll submit a pull request on a couple other files that I've edited in that folder right now, so only the TPI.py file will change in the next few hours.

**Comment by evan-magnusson** [comment]
Everything is up to date.

**Comment by evan-magnusson** [comment]
@talumbau 
I've finished messing with that folder -- I just edited TPI.py today.  I'm done changing it.

**Comment by talumbau** [comment]
the `dynamic` Package has been created.
