### ISSUE TITLE
What is the best way to create inputs that would run the code to completion quickly?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/dynamic#78]
It's typically quite helpful to have a 'toy' dataset around that one can quickly use execute the code from start to finish. This serves as a reasonable 'smoke test' that lets one know that some code refactoring didn't do major damage. After such a 'smoke test', one would then typically go run the real test (which may take tens of minutes or more). This dataset only has to achieve two goals:

- it must be acceptable input for the code
- it should execute fairly quickly

It doesn't have to make mathematical sense as input, nor produce reasonable output. Issue https://github.com/OpenSourcePolicyCenter/dynamic/issues/42 seems to indicate that we could now choose a very small J and S - is that correct? If so, is this likely to make the fsolves faster? For example, we could set J=3 and S=8. Is it easy to describe how one would create such a 'mini-input'? If so, could someone sketch out the necessary steps? I could dig in here, I just wonder how much expertise one would need to create such an input dataset.

**Comment by evan-magnusson** [comment]
The way a couple of the files are set up, we need to get some updated data before we can change the size of J.  Mostly just the income profiles are holding that up.  There is only one thing (that I know of) holding us back on changing S, but if we don't really care about sensible input, that is quite easy to change as well.  If we only change those 2 items, and then use all the same parameter values as in run_simulation.py, that should work.

**Comment by jdebacker** [comment]
But if we don't need sensible output, just something to run, then we ought
to be able to have J=1.  We can make the e's such that the representative
households' income is flat or not- I don't see why it wouldn't converge
either way.  But we should of course not be trying to match the data with
this (i.e. to the extent the chi_b, chi_n estimation runs, we should just
fit a distribution of hours/wealth that is pretty even).

**Comment by talumbau** [comment]
for better or worse, I came up with this:

https://github.com/OpenSourcePolicyCenter/dynamic/pull/84

seems to work ok for now.
