### ISSUE TITLE
Is `e_final` normalized properly?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/dynamic#83]
In the comments for `get_e`, we see that the returned matrix `e` of shape `S`x`J` is "normalized so the mean is one." However, neither the rows nor the columns of `e` have mean 1, which can be seen easily just by running the latest master and setting a breakpoint before `return e_final`. This is likely a trivial issue, but I just wanted to point it out. Perhaps I'm missing something eles?....

**Comment by evan-magnusson** [comment]
@talumbau It should really be "normalized so the weighted sum is one."  When multiplied by omega_SS and summed over all dimensions, it should be one.

**Comment by evan-magnusson** [comment]
I just checked it, it's correct as is.

**Comment by talumbau** [comment]
Does the comment in the code reflect your comments in this issue? If yes, please re-close. Otherwise, we should issue a PR against this issue.

**Comment by evan-magnusson** [comment]
Yep, that's been changed.  It'll be in the next [large] pull request.
