### ISSUE TITLE
Merge all Python folders into one

### ISSUE THREAD

**Issue by evan-magnusson** [OpenSourcePolicyCenter/dynamic#85]
Instead of having tested and multiple development folders for python code, we'll want to just have one folder where the code is stored, and utilize branches to handle different versions/projects. 
Checklist:
- [x] Get Development_firmproblem up to date, with all bug fixes finished and solved
- [x] Delete the Development_fsolve and TESTED_DONT_TOUCH folders
- [x] Transfer the changes in Development_firmproblem into the dynamic folder that @talumbau is working on, since that code will not have many of the changes we've implemented in the past few weeks
- [x] Delete CURRENT_DEBUGGED_VERSION folder

**Comment by evan-magnusson** [comment]
@talumbau I'm about finished with the bug fixes in the code -- are you still working on what is in the dynamic folder?  Whenever you're ready, I can get started on moving over the bug fixes.

**Comment by evan-magnusson** [comment]
Being done in PR #94 .

**Comment by talumbau** [comment]
go ahead and have it. I have no outstanding changes to merge in. I can help with review when you are ready for someone to have a look at it. this is good timing as I hope to dig back in to this with additional changes after PyData conference this weekend.

**Comment by evan-magnusson** [comment]
Finished, see PR #94 .
